### ISSUE TITLE
Reporting Missing Code in Project

### ISSUE THREAD

**Issue by dizhima** [leob03/E2E_Object_Pose_Estimator#1]
Firstly, I want to express my appreciation for the fantastic work on this project. It's been an invaluable resource, and I'm grateful for the effort put into it.

I've come across a couple of issues where it seems there might be some missing code:

utils/init.py - Line 1
The "submit" module from line 1 of `utils/__init__.py` appears to be missing or is not importable.

utils/PROPSPoseDataset.py - Line 14
The "rob599" module referenced on line 14 of `utils/PROPSPoseDataset.py`  also seems to be missing.  

Could you verify if these modules are supposed to be part of the project and, if so, include them in the repository?

I hope this feedback is helpful, and thank you for your attention to this matter.

**Comment by leob03** [comment]
Hi @dizhima, thank you very much for your feedback and sorry for this very late reply...

Indeed, I have changed the names of some of the files and folders which created those errors that you have encountered. If you pull the repo to get the modifications that I just did those errors should fixed. Thanks again for letting me know!
